# Generated by Django 4.2.2 on 2024-08-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='lon',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='qualifications',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
